version: '3'
services:   
  nproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nproxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - webgis
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
volumes:
  data:
  letsencrypt:
networks:
  webgis:
    external: true